
modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/MrCloudYT/First-Minecraft-Mod/issues" #optional

[[mods]] #mandatory

modId="craftingmod" #mandatory

version="1.16.1-0.3.0" #mandatory

displayName="Crafting Mod" #mandatory

updateJSONURL="https://github.com/MrCloudYT/First-Minecraft-Mod/" #optional

displayURL="https://github.com/MrCloudYT/First-Minecraft-Mod/" #optional

logoFile="ruby.png" #optional

credits="Forge for the MDK" #optional

authors="Mr Cloud" #optional

description='''
A Mod with custom crafting receipts/missing crafting receipes. It also adds "missing" crafting receipes.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,16.1]"
    ordering="NONE"
    side="BOTH"

